### ISSUE TITLE
v2rayNG 处理 tls + websocket 频繁断开 （VPN图标时隐时现）

### ISSUE THREAD

**Issue by gmsh** [v2ray/V2RayNG#1]
服务器端使用 nginx (tls) 反向代理，v2ray 使用 websocket 传入连接
客户端使用 websocket + tls 传出连接。
症状：windows 客户端可以连接，正常使用； v2rayNG 点击连接后 vpn 图标在状态栏时隐时现。
补充：v2rayNG 配置 websocket (without tls) 可以正常使用
服务器 v2ray 版本：2.38
windows 客户端版本：2.38
v2rayNG 版本：0.1.8
nginx配置：
![nginx](https://user-images.githubusercontent.com/396089/30782560-1d53aafc-a167-11e7-88e6-d300682aede3.png)
服务器端配置：
![server](https://user-images.githubusercontent.com/396089/30782558-1d504592-a167-11e7-957d-01762d565e9b.png)
v2rayNG配置：
![v2rayng](https://user-images.githubusercontent.com/396089/30782561-1da245ea-a167-11e7-8e8e-3aaed3bc34ef.jpg)
windowsk客户端配置：
![windows-client](https://user-images.githubusercontent.com/396089/30782559-1d51336c-a167-11e7-9318-57bad82a1518.png)
android 版本: 7.0.0
手机型号：三星 s8 plus

**Comment by DarienRaymond** [comment]
这个项目目前没有开发人员维护，所有相关问题都得不到解决。如果你认为这是core的问题，可以在v2ray-core那边提issue。v2rayNG的问题一时半会修不了。
